### ISSUE TITLE
Continued Inability to set the CK3 game folder as a library

### ISSUE THREAD

**Issue by SeamusFD** [DragonKnightOfBreeze/Paradox-Language-Support#8]
As stated before. I am still unable to set the CK3 game folder as a library.
![image](https://user-images.githubusercontent.com/6413824/215140824-debc15f7-dce2-4223-8f6e-a715acd31221.png)

**Comment by DragonKnightOfBreeze** [comment]
2 questions:* click the folder icon button on the screenshot and then click the top-right 'game directory' icon button on the dialog, which dir ('Crusader Kings III' or 'game') is choosed?
* for library path choose 'Crusader&nbsp; Kings III ' rather than 'game' directory, is it ok?
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月28日(星期六) 凌晨0:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [DragonKnightOfBreeze/Paradox-Language-Support] Continued Inability to set the CK3 game folder as a library (Issue #8)





 
As stated before. I am still unable to set the CK3 game folder as a library.

**Comment by SeamusFD** [comment]
I have tried both the regular 'game' folder and the top 'Crusader Kings III' folder. None of them work.

**Comment by DragonKnightOfBreeze** [comment]
Will be fixed on 0.7.13, optimize the logic to check game / mod directory.

**Comment by DragonKnightOfBreeze** [comment]
Fixed on 0.7.13,
for cwt ck3 config is not very perfect and the Paradox-language is so tricky,
 some advanced features are not supported (e.g. localisation_command).

Select 'Crusader Kings III' or just click 'Quick select' link on the dialog pls.
